server.port: 9090

spring:
  cloud:
    function:
      definition: customerOnboardFunction
    stream:
      output-bindings: fooSupplier-out-0
      bindings:
        customerOnboardFunction-in-0:
          destination: user-signup-topic
          consumer:
            use-native-decoding: true
        customerOnboardFunction-out-0:
          destination: customer-onboard-topic
          producer:
            use-native-encoding: true
      pulsar:
        bindings:
          customerOnboardFunction-in-0:
            consumer:
              schema-type: JSON
              message-type: org.springframework.pulsar.sample.signup.model.Signup
          customerOnboardFunction-out-0:
            producer:
              schema-type: JSON
              message-type: org.springframework.pulsar.sample.signup.model.CustomerCard
